# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the FixDev branch
  push:
    branches: [ FixDev ]
  pull_request:
    branches: [ FixDev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - if: github.ref == 'refs/heads/FixDev'
        name: set env variable if in DEV Branch
        env:
          URL: http://fixdev.com
      - if: github.ref == 'refs/heads/main'
        name: set env variable if in PROD Branch
        env:
          URL: http://prod.com
      - run: echo ${URL}  

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
